apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/flickpay_users
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
