apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:
        - name: user-service
          image: flickpay/user-service:local
          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: SPRING_DATASOURCE_DRIVER_CLASS_NAME

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: SPRING_DATASOURCE_PASSWORD
